require 'CampaignManagementService.rb'
require 'CampaignManagementServiceMappingRegistry.rb'
require 'soap/rpc/driver'

class ICampaignManagementService < ::SOAP::RPC::Driver
  DefaultEndpointUrl = "https://adcenterapi.microsoft.com/Api/Advertiser/v7/CampaignManagement/CampaignManagementService.svc"

  Methods = [
    [ "UpdateBehavioralBids",
      "updateBehavioralBids",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "UpdateBehavioralBidsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "UpdateBehavioralBidsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetCustomSegments",
      "getCustomSegments",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetCustomSegmentsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetCustomSegmentsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "AddSegments",
      "addSegments",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "AddSegmentsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "AddSegmentsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "DeleteSegments",
      "deleteSegments",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "DeleteSegmentsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "DeleteSegmentsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetSegmentsByIds",
      "getSegmentsByIds",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetSegmentsByIdsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetSegmentsByIdsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetSegments",
      "getSegments",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetSegmentsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetSegmentsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "SetUsersToSegments",
      "setUsersToSegments",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "SetUsersToSegmentsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "SetUsersToSegmentsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "DeleteUsersFromSegment",
      "deleteUsersFromSegment",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "DeleteUsersFromSegmentRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "DeleteUsersFromSegmentResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetNormalizedStrings",
      "getNormalizedStrings",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetNormalizedStringsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetNormalizedStringsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetKeywordEditorialReasonsByIds",
      "getKeywordEditorialReasonsByIds",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetKeywordEditorialReasonsByIdsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetKeywordEditorialReasonsByIdsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetAdEditorialReasonsByIds",
      "getAdEditorialReasonsByIds",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetAdEditorialReasonsByIdsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetAdEditorialReasonsByIdsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetNetworksByAdGroupIds",
      "getNetworksByAdGroupIds",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetNetworksByAdGroupIdsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetNetworksByAdGroupIdsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "SetNetworksToAdGroups",
      "setNetworksToAdGroups",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "SetNetworksToAdGroupsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "SetNetworksToAdGroupsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "AddAds",
      "addAds",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "AddAdsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "AddAdsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"EditorialApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"EditorialApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "DeleteAds",
      "deleteAds",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "DeleteAdsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "DeleteAdsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetAdsByEditorialStatus",
      "getAdsByEditorialStatus",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetAdsByEditorialStatusRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetAdsByEditorialStatusResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetAdsByIds",
      "getAdsByIds",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetAdsByIdsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetAdsByIdsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetAdsByAdGroupId",
      "getAdsByAdGroupId",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetAdsByAdGroupIdRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetAdsByAdGroupIdResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "UpdateAds",
      "updateAds",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "UpdateAdsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "UpdateAdsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"EditorialApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"EditorialApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "PauseAds",
      "pauseAds",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "PauseAdsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "PauseAdsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "ResumeAds",
      "resumeAds",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "ResumeAdsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "ResumeAdsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "AddKeywords",
      "addKeywords",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "AddKeywordsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "AddKeywordsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"EditorialApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"EditorialApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "DeleteKeywords",
      "deleteKeywords",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "DeleteKeywordsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "DeleteKeywordsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetKeywordsByEditorialStatus",
      "getKeywordsByEditorialStatus",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetKeywordsByEditorialStatusRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetKeywordsByEditorialStatusResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetKeywordsByIds",
      "getKeywordsByIds",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetKeywordsByIdsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetKeywordsByIdsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetKeywordsByAdGroupId",
      "getKeywordsByAdGroupId",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetKeywordsByAdGroupIdRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetKeywordsByAdGroupIdResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "PauseKeywords",
      "pauseKeywords",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "PauseKeywordsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "PauseKeywordsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "ResumeKeywords",
      "resumeKeywords",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "ResumeKeywordsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "ResumeKeywordsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "UpdateKeywords",
      "updateKeywords",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "UpdateKeywordsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "UpdateKeywordsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"EditorialApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"EditorialApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetKeywordEstimatesByBids",
      "getKeywordEstimatesByBids",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetKeywordEstimatesByBidsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetKeywordEstimatesByBidsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "AddBusinesses",
      "addBusinesses",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "AddBusinessesRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "AddBusinessesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "UpdateBusinesses",
      "updateBusinesses",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "UpdateBusinessesRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "UpdateBusinessesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "DeleteBusinesses",
      "deleteBusinesses",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "DeleteBusinessesRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "DeleteBusinessesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetBusinessesInfo",
      "getBusinessesInfo",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetBusinessesInfoRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetBusinessesInfoResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetBusinessesByIds",
      "getBusinessesByIds",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetBusinessesByIdsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetBusinessesByIdsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "AddSitePlacements",
      "addSitePlacements",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "AddSitePlacementsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "AddSitePlacementsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "DeleteSitePlacements",
      "deleteSitePlacements",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "DeleteSitePlacementsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "DeleteSitePlacementsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetSitePlacementsByIds",
      "getSitePlacementsByIds",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetSitePlacementsByIdsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetSitePlacementsByIdsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetSitePlacementsByAdGroupId",
      "getSitePlacementsByAdGroupId",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetSitePlacementsByAdGroupIdRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetSitePlacementsByAdGroupIdResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "PauseSitePlacements",
      "pauseSitePlacements",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "PauseSitePlacementsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "PauseSitePlacementsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "ResumeSitePlacements",
      "resumeSitePlacements",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "ResumeSitePlacementsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "ResumeSitePlacementsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "UpdateSitePlacements",
      "updateSitePlacements",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "UpdateSitePlacementsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "UpdateSitePlacementsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetPlacementDetailsForUrls",
      "getPlacementDetailsForUrls",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetPlacementDetailsForUrlsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetPlacementDetailsForUrlsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "AddBehavioralBids",
      "addBehavioralBids",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "AddBehavioralBidsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "AddBehavioralBidsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "DeleteBehavioralBids",
      "deleteBehavioralBids",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "DeleteBehavioralBidsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "DeleteBehavioralBidsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetBehavioralBidsByIds",
      "getBehavioralBidsByIds",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetBehavioralBidsByIdsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetBehavioralBidsByIdsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetBehavioralBidsByAdGroupId",
      "getBehavioralBidsByAdGroupId",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetBehavioralBidsByAdGroupIdRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetBehavioralBidsByAdGroupIdResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "PauseBehavioralBids",
      "pauseBehavioralBids",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "PauseBehavioralBidsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "PauseBehavioralBidsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "ResumeBehavioralBids",
      "resumeBehavioralBids",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "ResumeBehavioralBidsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "ResumeBehavioralBidsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "AddCampaigns",
      "addCampaigns",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "AddCampaignsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "AddCampaignsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetCampaignsByAccountId",
      "getCampaignsByAccountId",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetCampaignsByAccountIdRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetCampaignsByAccountIdResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetCampaignsByIds",
      "getCampaignsByIds",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetCampaignsByIdsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetCampaignsByIdsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "PauseCampaigns",
      "pauseCampaigns",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "PauseCampaignsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "PauseCampaignsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "ResumeCampaigns",
      "resumeCampaigns",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "ResumeCampaignsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "ResumeCampaignsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "DeleteCampaigns",
      "deleteCampaigns",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "DeleteCampaignsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "DeleteCampaignsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "UpdateCampaigns",
      "updateCampaigns",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "UpdateCampaignsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "UpdateCampaignsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetCampaignsInfoByAccountId",
      "getCampaignsInfoByAccountId",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetCampaignsInfoByAccountIdRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetCampaignsInfoByAccountIdResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetNegativeKeywordsByCampaignIds",
      "getNegativeKeywordsByCampaignIds",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetNegativeKeywordsByCampaignIdsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetNegativeKeywordsByCampaignIdsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "SetNegativeKeywordsToCampaigns",
      "setNegativeKeywordsToCampaigns",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "SetNegativeKeywordsToCampaignsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "SetNegativeKeywordsToCampaignsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "AddAdGroups",
      "addAdGroups",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "AddAdGroupsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "AddAdGroupsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "DeleteAdGroups",
      "deleteAdGroups",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "DeleteAdGroupsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "DeleteAdGroupsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetAdGroupsByIds",
      "getAdGroupsByIds",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetAdGroupsByIdsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetAdGroupsByIdsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetAdGroupsByCampaignId",
      "getAdGroupsByCampaignId",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetAdGroupsByCampaignIdRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetAdGroupsByCampaignIdResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "PauseAdGroups",
      "pauseAdGroups",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "PauseAdGroupsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "PauseAdGroupsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "ResumeAdGroups",
      "resumeAdGroups",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "ResumeAdGroupsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "ResumeAdGroupsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "SubmitAdGroupForApproval",
      "submitAdGroupForApproval",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "SubmitAdGroupForApprovalRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "SubmitAdGroupForApprovalResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "UpdateAdGroups",
      "updateAdGroups",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "UpdateAdGroupsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "UpdateAdGroupsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetAdGroupsInfoByCampaignId",
      "getAdGroupsInfoByCampaignId",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetAdGroupsInfoByCampaignIdRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetAdGroupsInfoByCampaignIdResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetNegativeKeywordsByAdGroupIds",
      "getNegativeKeywordsByAdGroupIds",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetNegativeKeywordsByAdGroupIdsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetNegativeKeywordsByAdGroupIdsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "SetNegativeKeywordsToAdGroups",
      "setNegativeKeywordsToAdGroups",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "SetNegativeKeywordsToAdGroupsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "SetNegativeKeywordsToAdGroupsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "AddTarget",
      "addTarget",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "AddTargetRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "AddTargetResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "DeleteTarget",
      "deleteTarget",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "DeleteTargetRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "DeleteTargetResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetTargetByAdGroupId",
      "getTargetByAdGroupId",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetTargetByAdGroupIdRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetTargetByAdGroupIdResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "UpdateTarget",
      "updateTarget",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "UpdateTargetRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "UpdateTargetResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "AddTargetsToLibrary",
      "addTargetsToLibrary",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "AddTargetsToLibraryRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "AddTargetsToLibraryResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "UpdateTargetsInLibrary",
      "updateTargetsInLibrary",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "UpdateTargetsInLibraryRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "UpdateTargetsInLibraryResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "DeleteTargetsFromLibrary",
      "deleteTargetsFromLibrary",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "DeleteTargetsFromLibraryRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "DeleteTargetsFromLibraryResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetTargetsInfoFromLibrary",
      "getTargetsInfoFromLibrary",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetTargetsInfoFromLibraryRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetTargetsInfoFromLibraryResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetTargetsByIds",
      "getTargetsByIds",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetTargetsByIdsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetTargetsByIdsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "SetTargetToAdGroup",
      "setTargetToAdGroup",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "SetTargetToAdGroupRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "SetTargetToAdGroupResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "DeleteTargetFromAdGroup",
      "deleteTargetFromAdGroup",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "DeleteTargetFromAdGroupRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "DeleteTargetFromAdGroupResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetTargetsByAdGroupIds",
      "getTargetsByAdGroupIds",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetTargetsByAdGroupIdsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetTargetsByAdGroupIdsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "SetTargetToCampaign",
      "setTargetToCampaign",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "SetTargetToCampaignRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "SetTargetToCampaignResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "DeleteTargetFromCampaign",
      "deleteTargetFromCampaign",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "DeleteTargetFromCampaignRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "DeleteTargetFromCampaignResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ],
    [ "GetTargetsByCampaignIds",
      "getTargetsByCampaignIds",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetTargetsByCampaignIdsRequest"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "https://adcenter.microsoft.com/v7", "GetTargetsByCampaignIdsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"ApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"ApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}, "AdApiFaultDetailFault"=>{:namespace=>nil, :encodingstyle=>"document", :name=>"AdApiFaultDetailFault", :use=>"literal", :ns=>"https://adcenter.microsoft.com/v7"}} }
    ]
  ]

  def initialize(endpoint_url = nil)
    endpoint_url ||= DefaultEndpointUrl
    super(endpoint_url, nil)
    self.mapping_registry = CampaignManagementServiceMappingRegistry::EncodedRegistry
    self.literal_mapping_registry = CampaignManagementServiceMappingRegistry::LiteralRegistry
    init_methods
  end

private

  def init_methods
    Methods.each do |definitions|
      opt = definitions.last
      if opt[:request_style] == :document
        add_document_operation(*definitions)
      else
        add_rpc_operation(*definitions)
        qname = definitions[0]
        name = definitions[2]
        if qname.name != name and qname.name.capitalize == name.capitalize
          ::SOAP::Mapping.define_singleton_method(self, qname.name) do |*arg|
            __send__(name, *arg)
          end
        end
      end
    end
  end
end

